<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: lookup_value_edit_fns.inc,v 1.3 2006/12/06 01:07:34 emcdonald Exp $
*
*/

require_once SQ_INCLUDE_PATH.'/asset_edit/asset_edit_fns.inc';


/**
* Lookup_Value_Edit_Fns
*
* Dummy edit functions for Lookup_Value, as Lookup Values are not instantiated.
*
*
* @author	Blair Robertson <brobertson@squiz.co.uk>
* @version $Revision: 1.3 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Lookup_Value_Edit_Fns extends Asset_Edit_Fns
{

}//end class

?>
