TRUNCATE sq_asset;
TRUNCATE sq_asset_attribute;
TRUNCATE sq_asset_attribute_value;
TRUNCATE sq_asset_link;
TRUNCATE sq_asset_link_tree;
TRUNCATE sq_asset_lookup;
TRUNCATE sq_asset_path;
TRUNCATE sq_asset_permission;
TRUNCATE sq_asset_type;
TRUNCATE sq_asset_type_inherited;
TRUNCATE sq_asset_url;
TRUNCATE sq_internal_message;
TRUNCATE sq_package;
DROP SEQUENCE sq_sequence_asset_attribute_seq;
DROP SEQUENCE sq_sequence_asset_seq;
DROP SEQUENCE sq_sequence_asset_link_seq;
DROP SEQUENCE sq_sequence_internal_message_seq;
