TRUNCATE sq_asset;
TRUNCATE sq_asset_attribute;
TRUNCATE sq_asset_attribute_value;
TRUNCATE sq_asset_link;
TRUNCATE sq_asset_type;
TRUNCATE sq_asset_type_inherited;
TRUNCATE sq_asset_urls;
TRUNCATE sq_package;
DROP SEQUENCE sq_sequence_asset_attribute_seq;
DROP SEQUENCE sq_sequence_asset_seq;
DROP SEQUENCE sq_sequence_asset_link_seq;
