<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ABN 77 084 670 600                                                 |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.com.au) so we may provide|
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
*/
require_once SQ_CORE_PACKAGE_PATH.'/system/triggers/trigger_event/trigger_event_edit_fns.inc';
require_once SQ_CORE_PACKAGE_PATH.'/system/triggers/trigger_event/trigger_event.inc';

/**
* Trigger_Event_Form_Submission_Completed_Edit_Fns
*
* @author  Ash Karelia <akarelia@squiz.com.au>
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Event_Form_Submission_Completed_Edit_Fns extends Trigger_Event_Edit_Fns
{


}//end class

?>
