<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ABN 77 084 670 600                                                 |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.com.au) so we may provide|
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: version.inc,v 1.57.2.6 2013/06/26 00:36:35 ewang Exp $
*
*/

define('SQ_SYSTEM_VERSION',        '4.14.4');
define('SQ_SYSTEM_SHORT_NAME',     'MySource');
define('SQ_SYSTEM_LONG_NAME',      'Squiz Matrix v'.SQ_SYSTEM_VERSION);
define('SQ_SYSTEM_URL',            'http://matrix.squizsuite.net/');

define('SQ_REQUIRED_PHP_VERSION',  '5.1.6');
?>
