truncate sq_asset;
truncate sq_asset_attribute;
truncate sq_asset_attribute_default;
truncate sq_asset_attribute_value;
truncate sq_asset_link;
truncate sq_asset_type;
truncate sq_asset_type_inherited;
truncate sq_package;
drop table sq_sequence_asset_attribute_seq;
drop table sq_sequence_asset_seq;
