<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ABN 77 084 670 600                                                 |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.com.au) so we may provide|
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
*/

require_once SQ_INCLUDE_PATH.'/asset_management.inc';

/**
* Trigger_Action_Assign_User_To_Groups_Management
*
* @see Asset_Management
*
* @author  Ash Karelia <akarelia@squiz.net>
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Action_Assign_User_To_Groups_Management extends Asset_Management
{

}//end class
?>
