<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: trigger_action_set_standard_asset_date_edit_fns.inc,v 1.1.2.2 2010/04/01 02:19:52 lwright Exp $
*
*/


/**
* Trigger_Condition_Set_Standard_Asset_Date_Edit_Fns
*
* @author  Avi Miller <amiller@squiz.net>
* @version $Revision: 1.1.2.2 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Action_Set_Standard_Asset_Date_Edit_Fns extends Trigger_Action_Edit_Fns
{

}//end class

?>
