<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: trigger_event_public_user_session_created_edit_fns.inc,v 1.1.6.1 2010/09/16 04:57:59 ewang Exp $
*
*/
require_once SQ_CORE_PACKAGE_PATH.'/system/triggers/trigger_event/trigger_event_edit_fns.inc';
require_once SQ_CORE_PACKAGE_PATH.'/system/triggers/trigger_event/trigger_event.inc';

/**
* Trigger_Event_Public_User_Session_Created_Edit_Fns
*
* @author  James Hurst <jhurst@squiz.co.uk>
* @version $Revision: 1.1.6.1 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Event_Public_User_Session_Created_Edit_Fns extends Trigger_Event_Edit_Fns
{


}//end class

?>
