<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: trigger_event_public_user_session_created.inc,v 1.1 2009/07/20 16:31:49 jhurst Exp $
*
*/


/**
* Trigger Public User Session Created
*
* Fired after the user logs into Matrix
*
* @author  James Hurst <jhurst@squiz.co.uk>
* @version $Revision: 1.1 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Event_Public_User_Session_Created extends Trigger_Event
{

}//end class

?>
