<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: trigger_action_edit_fns.inc,v 1.3.20.1 2011/04/04 05:46:52 ewang Exp $
*
*/
require_once SQ_INCLUDE_PATH.'/asset_edit/asset_edit_fns.inc';

/**
* Trigger_Action_Edit_Fns
*
* Dummy edit functions for Trigger_Action, as Trigger Actions are not instantiated.
*
*
* @author  Andrei Railean <arailean@squiz.net>
* @author   Robert Howard <rhoward@squiz.net>
* @version $Revision: 1.3.20.1 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Action_Edit_Fns extends Asset_Edit_Fns
{


}//end class

?>
