<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: trigger_event_before_asset_deleted_edit_fns.inc,v 1.2 2006/12/05 23:49:49 bcaldwell Exp $
*
*/


/**
* Trigger_Event_Edit_Fns
*
* Edit functions for the event fired before an asset is deleted
*
*
* @author  Elden McDonald <emcdonald@squiz.net>
* @version $Revision: 1.2 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Event_Before_Asset_Deleted_Edit_Fns extends Trigger_Event_Edit_Fns
{


}//end class

?>
