<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: trigger_event_asset_cloned.inc,v 1.1.2.2 2012/04/24 04:01:38 akarelia Exp $
*
*/


/**
* Trigger Event Asset Cloned
*
* Fired after an asset has been cloned
*
*
* @author  Ash Karelia <akarelia@squiz.com.au>
* @version $Revision: 1.1.2.2 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Event_Asset_Cloned extends Trigger_Event
{

}//end class

?>
