<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: trigger_event_before_user_logout_edit_fns.inc,v 1.1 2008/10/23 22:57:40 akarelia Exp $
*
*/


/**
* Trigger_Event_Before_User_Logout_Edit_Fns
*
* @author  Ashish Karelia <akarelia@squiz.net>
* @version $Revision: 1.1 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Event_Before_User_Logout_Edit_Fns extends Trigger_Event_Edit_Fns
{


}//end class

?>
