<?php
/**
* +--------------------------------------------------------------------+
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +--------------------------------------------------------------------+
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +--------------------------------------------------------------------+
*
* $Id: trigger_action_delete_future_status_edit_fns.inc,v 1.2 2006/12/06 00:05:38 bcaldwell Exp $
*
*/


/**
* Trigger_Action_Delete_Future_Status_Edit_Fns
*
* @author  Andrei Railean <arailean@squiz.net>
* @author  Scott Kim <skim@squiz.net>
* @version $Revision: 1.2 $
* @package MySource_Matrix_Packages
* @subpackage __core__
*/
class Trigger_Action_Delete_Future_Status_Edit_Fns extends Trigger_Action_Edit_Fns
{

}//end class

?>
